import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Roboto from "next/font/google"
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        Roboto
      )}>{children}</body>
    </html>
  )
}
